Feat/33 documentation tidy up
flaxandteal/dewret pull request #44
Opened 2024-06-28 08:16 UTC by KamenDimitrov97

## Summary

This PR improves the Quickstart.md documentation for Dewret as discussed in [issue #33](https://github.com/flaxandteal/dewret/issues/33). The update creates an introduction to Dewret and attempts to answer the question Why use Dewret?

## Changes
- Introduction: Added a detailed description of Dewret, highlighting its purpose, features, and supported renderers (Snakemake and CWL).
- What are Workflows?: Explained the concept of workflows.
- Highlighted Dewret's unique features.
- Installation for Pure Users

2024-06-28 11:26 UTC, elleryames requested changes
Thanks @KamenDimitrov97 ! I've suggested a few edits to the text, but looks good.

2024-06-28 11:26 UTC, elleryames commented on docs/quickstart.md
> +Workflows are a collection of tasks or steps designed to automate complex processes. These processes are common in fields like data science and software development, where you can ensure automation.
> data science and software development

How about adding "scientific computing" to this list.

2024-06-28 11:26 UTC, elleryames commented on docs/quickstart.md
> +- Optimization: creating the workflow explicitly opens up possibilities for static analysis and refactoring before real execution.
> Optimization: creating the workflow explicitly opens up possibilities for static analysis and refactoring before real execution.

I like this start. Here is a suggested iteration: 

"Optimization: creating a declarative workflow opens up possibilities for static analysis and refactoring before execution."

2024-06-28 11:26 UTC, elleryames commented on docs/quickstart.md
> +- Customization: ability to create custom renderers in the required workflow language.
> - Customization: ability to create custom renderers in the required workflow language.

"- Customization: ability to create a custom renderer in a desired workflow language."

2024-06-28 12:56 UTC, KamenDimitrov97 commented on docs/quickstart.md
> +Dewret is a tool designed for creating complex workflows, written in a dynamic style, to be rendered to a static representation. It makes it easier for users to define tasks and organize them into wo
I'll just remove that if it's okay? Or would you like me to re-word it?

2024-06-28 14:06 UTC, elleryames commented on docs/quickstart.md
> +Dewret is a tool designed for creating complex workflows, written in a dynamic style, to be rendered to a static representation. It makes it easier for users to define tasks and organize them into wo
What about "Dewret provides a programmatic python interface to multiple ...."

2024-07-03 10:24 UTC, elleryames commented on docs/glossary.md
> +- To render a workflow is to generate an executable workflow in a specific workflow language such as and Snakemake.
> ... a specific workflow language such as and Snakemake.

I think this sentence is missing a "CWL" or has an extra "and".

2024-07-03 10:29 UTC, elleryames commented on docs/quickstart.md
> +- Git-versionable workflows: while code can be versioned, the changes of a dynamic workflow do not necessarily clearly correspond to changes in the executed workflow. This maintains a precise trackab
> This maintains a precise trackable history.

I think we can further clarify the "This" in this sentence. I think we mean the creation of a static workflow definition, which is rendered from the dynamic or programmatic workflow. Is there a succinct way to write this?

2024-07-03 10:32 UTC, elleryames commented on docs/quickstart.md
> +- Customization: ability to create a custom renderer in a desired workflow language.
Yeah, agreed. The ability to render a single workflow into multiple different declarative workflow languages is very nice. It might allow users to try out a given workflow on different workflow engines. I think we can move the mention of default (available) renderers CWL and Snakemake up here.

2024-07-03 10:35 UTC, elleryames commented on docs/quickstart.md
> +- Debugging: a number of classes of workflow planning bugs will not appear until late in a simulation run that might take days or weeks. This catches them before startup.
Again, the "This" can be clarified. It could refer to the static type checking provided by `dewret` (the extent of which is under discussion), or perhaps more generally the possibilities for static analysis afforded by having declarative and static workflow definition document post render.

2024-07-03 11:38 UTC, KamenDimitrov97 commented on docs/quickstart.md
> +- Customization: ability to create a custom renderer in a desired workflow language.
Are you referring to the Optimization bullet point?

2024-07-17 11:14 UTC, elleryames approved these changes
Thanks for this @KamenDimitrov97 !

2024-07-18 12:01 UTC, merged