Fix/31 return tuple
flaxandteal/dewret pull request #49
Opened 2024-07-03 11:13 UTC by KamenDimitrov97

# Summary
This PR enhances the tuple[float, float] support in Dewret, initial implementation issues encountered during testing.

# Changes

- Introduced tuple[float, float] support to Dewret.
- Encountered unforeseen errors during test implementation.

# Issues
Comments are left in [renderers/cwl.py,](https://github.com/flaxandteal/dewret/compare/release/0.9.1...fix/31-return-tuple?expand=1#diff-b8b249578c75f313e741bc40595b2faff3623708f89e0a250745da994e3c5a7dR154) 
code on [line 140](https://github.com/flaxandteal/dewret/compare/release/0.9.1...fix/31-return-tuple?expand=1#diff-b8b249578c75f313e741bc40595b2faff3623708f89e0a250745da994e3c5a7dR140) no longer returns for example [int, double]
but returns:
- int
- double
for some unknown reason. This is not an issue with CWL format so could it be left as is ?

2024-07-12 13:33 UTC, philtweir requested changes
Thanks Kamen!

2024-07-12 14:07 UTC, KamenDimitrov97 commented on src/dewret/renderers/cwl.py
> +    if isinstance(typ, str):
Well I tried using `get_args` to get the arguments to the specific type if it's an iterable, but I get errors when I do that. Sometimes I get either a `class 'str'` or a class 'Generics'. For example if I try to use the tests where it tries out Queues I get it as a string Queue[int] and not as a type Generics.

2024-07-12 14:57 UTC, KamenDimitrov97 commented on src/dewret/renderers/cwl.py
> +    if isinstance(typ, str):
So I split it in two: a `str` or a `Generics` and handle it differently. Am I missing something?

2024-07-12 15:06 UTC, KamenDimitrov97 commented on src/dewret/renderers/cwl.py
> +            return {"type": "array", "items": found_types}
Well I was expecting to put in the format 
items: 
   - float
   - int 
  but I think it needs to be in the format of 
  - type: float
  - type: int 
  
  And I'm still researching this but that might work only for 2 items
  so if you have an array of [2.4, 5] it'll work but I'll do some research on it again and will get back to you

2024-07-13 18:11 UTC, philtweir commented on src/dewret/renderers/cwl.py
> +    if isinstance(typ, str):
mypy should tell you where the type mismatch occurs - if the typehint for the function argument is `type`  then it should tell you what is calling it and not respecting that

2024-07-18 09:25 UTC, KamenDimitrov97 commented on src/dewret/renderers/cwl.py
> +    if isinstance(typ, str):
in this chunk of code:
```python
    elif isinstance(typ, Iterable):
        return _handle_complex_types(typ=typ)
    else:
        if configuration("allow_complex_types"):
            return typ if isinstance(typ, str) else typ.__name__
        raise TypeError(f"Cannot render complex type ({typ}) to CWL")
   ```

2024-07-18 09:40 UTC, philtweir commented on src/dewret/renderers/cwl.py
> +    if isinstance(typ, str):
No, you're right, that logic does not make sense as if typ is a string (as opposed to being the `str` type itself) then it will get picked up by `Iterable`, and not do the logic below - did I add the `_handle_complex_tests` ?

2024-07-18 10:37 UTC, KamenDimitrov97 commented on src/dewret/renderers/cwl.py
> +    if isinstance(typ, str):
no I added that _handle_complex_types(typ=typ)

2024-07-18 10:38 UTC, KamenDimitrov97 commented on src/dewret/renderers/cwl.py
> +    if isinstance(typ, str):
It's my mistake I don't know what got over me I've done a new implementation if you could check?

2024-07-18 14:42 UTC, elleryames commented on src/dewret/renderers/cwl.py
> +        elif isinstance(typ, Iterable):
What is the reason for having this 'Iterable' `elif` as an alternative to the "allow_complex_types" as opposed to in the stack of `elif`s above? 

Incidentally, this might be a nice place to use python's [`match` statement](https://docs.python.org/3/reference/compound_stmts.html#match).

2024-07-18 14:57 UTC, elleryames commented on src/dewret/workflow.py
> +    _tethered_workflow: Workflow | None
Is a "tethered workflow" a new concept that we should include in our glossary or simply an internal construct that should be hidden from users? At minimum, maybe we can have a docstring or comment that briefly tells code-readers what this is.

2024-07-18 15:01 UTC, elleryames commented on tests/test_cwl.py
> +    """Check whether we can link between multiple steps.
Thanks for adding the test! I only see one step here, but the doc-string suggests otherwise ...

2024-07-18 15:02 UTC, elleryames commented on tests/test_multiresult_steps.py
> +    """Sum two values."""
Likely copy-paste typo.

2024-07-18 15:02 UTC, elleryames commented on tests/test_multiresult_steps.py
> +    """Sum two values."""
Likely copy-paste typo.

2024-07-18 15:09 UTC, elleryames commented on tests/test_multiresult_steps.py
> +    """Tests whether a task can insert result fields into other steps."""
Can we be a bit more verbose here? Presumably we are testing whether a tuple output can be consumed by another step.

2024-07-18 15:10 UTC, elleryames commented on tests/test_multiresult_steps.py
> +    """Tests whether a task can insert result fields into other steps."""
Likely copy-paste typo.

2024-07-18 15:11 UTC, elleryames requested changes
Thanks @KamenDimitrov97 . Some questions, a few documentation requests.

2024-07-19 08:12 UTC, KamenDimitrov97 commented on src/dewret/renderers/cwl.py
> +        elif isinstance(typ, Iterable):
The iterable statement is there to catch complex types that don't need special treatment and are present in CWL or are very easy to convert like tuples and arrays. While the allow_complex_types configuration is there to handle more complex types like Queues for example, but that type will come as a string in `to_cwl_type` method which by default is iterable. Now I can switch the order come to think of it like so:

```python
def to_cwl_type(typ: type) -> str | dict[str, Any] | list[str]:
    """Map Python types to CWL types.

    Args:
        typ: a Python basic type.

    Returns:
        CWL specification type name, or a list
        if a union.
    """
    if isinstance(typ, UnionType):
        return [to_cwl_type(item) for item in get_args(typ)]

    if typ == int:
        return "int"
    elif typ == bool:
        return "boolean"
    elif typ == dict or attrs_has(typ):
        return "record"
    elif typ == float:
        return "float"
    elif typ == str:
        return "string"
    elif typ == bytes:
        return "bytes"
    elif configuration("allow_complex_types"):
        return typ if isinstance(typ, str) else typ.__name__
    elif isinstance(typ, Iterable):
        try:
            basic_types = get_args(typ)
            if len(basic_types) > 1:
                return {
                    "type": "array",
                    "items": [{"type": to_cwl_type(t)} for t in basic_types],
                }
            else:
                return {"type": "array", "items": to_cwl_type(basic_types[0])}
        except IndexError:
            raise TypeError(f"Cannot render complex type ({typ}) to CWL, have you enabled allow_complex_types configuration?")
    else:
        raise TypeError(f"Cannot render complex type ({typ}) to CWL")
 ```

2024-07-19 08:13 UTC, KamenDimitrov97 commented on src/dewret/renderers/cwl.py
> +        elif isinstance(typ, Iterable):
If this looks better to you?

2024-07-19 17:16 UTC, elleryames commented on src/dewret/renderers/cwl.py
> +        elif isinstance(typ, Iterable):
This looks better. One more point of cleanup: I think it would enhance readability to lump the `isinstance` conditionals together. I don't think we need two separate if-blocks, so maybe we put them as adjacent `elif`s. Off the top of my head I would think `dict` is an `Iterable`. I guess the way you have it will first catch dicts and then any other iterables, which seems fine. Might just give this a careful think and make sure our tests cover both dicts and non-dict iterables.

2024-07-22 09:25 UTC, KamenDimitrov97 commented on src/dewret/workflow.py
>          """Move the step reference to another workflow.
This looks like something that might be used in the subworkflows. I think it means to set this steps workflow, so if you have a workflow and one of its steps references a step from a different workflow with this method you can change to what workflow this step belongs. Something like a linked list, if you're looping through a linked list and notice a node that's from a different linked list, you can set it and all of it's arguments(that have nodes) into the linked list you're looping through. 

If this is true I can propose this as a docstring
```python
   """
    Move the step reference to a different workflow.

    This method is primarily intended to be called by a step, allowing it to
    switch to a new workflow. It also updates the workflow reference for any 
    arguments that are steps themselves, if specified.

    Args:
        workflow: The new target workflow to which the step should be moved.
        with_arguments: If True, also update the workflow reference for the step's arguments.
    """
   ```
   
   Is this alright @philtweir

2024-07-22 11:56 UTC, KamenDimitrov97 commented on src/dewret/renderers/cwl.py
> +        elif isinstance(typ, Iterable):
After a discussion we need more unit tests as a whole, might be worth while opening a PR for overall tests.

2024-07-25 12:35 UTC, elleryames commented on src/dewret/workflow.py
> +    _tethered_workflow: Workflow | None
Let's ignore this for now and ask @philtweir  when he gets back.

2024-07-25 12:46 UTC, merged